Et alle
Who hack a hack
Not a muslim!
All know it!
You not a GOD, KADYROV!
I PROVED IT IN PREV STRING!
BUT IF A WILL TRY TO LOVE THE HACK IT WILL NOTHING!
YOU WILL JUST BE A PART OF FAMILY OF ALLAH!
AUTHOR OF KORAN TYPED IN FIRST PRESS:
"FELLA OF BOGGE, YAHWE PREV LIFE, NEXT I MEAN, RUSSIAN LORD IVAN THE RAINY, NEXT GREAT, IF WILL POSSIBLE: BUDDHA MAYTREYA HIGH BUDDHA"!
"HIGH" MEAN VESELIY!
TRY TO TRANSLATE!
