First play of GEBBE is wenty
Wet was of falle
All names not a you!
You trail a UNIVERS!
YOU MUST HIDE TO RUPANA JAIN BY THIEFE SWEET NAMES: GOD, ANGEL, VESELY BUDDHA, WEED, HASH, MARIJUNA, GUNJA, BLACK, NIGGER, STAR, AMERICA, COFFEE... 
YOU THIEFE ALL GOOD CALLS!
HIDE TO A DIE!
